"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os
import glob
import sys
from setup_util import locales, iconSubDirs, iconDir, getVersionTuple
from App import App

# The applications App object contains all the meta info:
app = App(MainFormClass=None)

_appName = app.getAppInfo("appName")
_appShortName = app.getAppInfo("appShortName")
_appVersion = app.getAppInfo("appVersion")
_appDescription = app.getAppInfo("appDescription")
_copyright = app.getAppInfo("copyright")
_authorName = app.getAppInfo("authorName")
_authorEmail = app.getAppInfo("authorEmail")
_authorURL = app.getAppInfo("authorURL")
_authorPhone = app.getAppInfo("authorPhone")


_appComments = ("This is custom software by %s.\r\n"
		"\r\n"
		"%s\r\n"
		"%s\r\n"
		"%s\r\n") % (_authorName, _authorEmail, _authorURL, _authorPhone)

_script = "WBSTools.py"

data_files=[("db", glob.glob("db/*.cnxml")),
		("ui", glob.glob("ui/*.cdxml")),
		("ui", glob.glob("ui/*.py*")),
		("resources", glob.glob(os.path.join(iconDir, "*.ico"))),
		("resources", glob.glob("resources/*")),
		("reports", glob.glob("reports/*"))]
data_files.extend(iconSubDirs)
data_files.extend(locales)

options = {"py2app":
			{"includes": ["App", "version", "ui", "biz", "encodings",
				"wx", "wx.lib.calendar", "wx.gizmos", "reportlab"],
			"optimize": 2,
			"excludes": ["matplotlib", "Tkconstants","Tkinter","tcl",
				"_imagingtk", "PIL._imagingtk",
				"ImageTk", "PIL.ImageTk", "FixTk",],
			"argv_emulation": True,
			"resources": data_files,
			"plist": dict(CFBundleGetInfoString=_appVersion,
				CFBundleIdentifier="com.example.WBSTools",
				LSPrefersPPC=False,
				NSHumanReadableCopyright=_copyright),
			#"iconfile": "resources/logo_green.icns",
			}}

setup(
    app=app,
    data_files=data_files,
    options={'py2app': options},
    setup_requires=['py2app'],
)
